<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <PackageId>OctopusEnergy.Client</PackageId>
    <Version>1.0.3</Version>
    <Authors>Mark Heydon</Authors>
    <Description>Unofficial .NET client for the Octopus Energy customer REST API. Not affiliated with Octopus Energy.</Description>
    <PackageProjectUrl>https://markheydon.me.uk/octopus-energy-dotnet/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/markheydon/octopus-energy-dotnet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>octopus-energy;kraken;energy;api;client</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OctopusEnergy.Client.Tests" />
  </ItemGroup>

</Project>
